### ISSUE TITLE
Illegible world-writable directories

### ISSUE THREAD

**Issue by pceiley** [Ghosh/hyperterm-solarized-dark#10]
Directories that have been set world writable are almost illegible.  I'm using Hyper on Windows 10 (bash on Ubuntu on Windows).
![solarized-illegible-dirs](https://cloud.githubusercontent.com/assets/1720468/24386092/5ec626d6-13b9-11e7-9d91-ff545337aa4f.png)

**Comment by ghosh** [comment]
@pceiley Hi, are you still having this issue? I am not being able to recreate this on my machine. Here is how it looks on mine:-

<img width="643" alt="screen shot 2017-04-15 at 1 16 49 am" src="https://cloud.githubusercontent.com/assets/4667682/25054185/5364c090-2179-11e7-8bbb-31893d008d3a.png">

**Comment by pceiley** [comment]
Yes still having this issue.  Anything I can provide to help troubleshoot?

**Comment by chilblane** [comment]
@ghosh Can you use the dev tools to inspect that span in the `x-row` and see what colors it's using? For me and for @pceiley, the inline styles on the span render as
```
color: #268bd2;
background-color: #859900;
```
which are `colors.blue` and `colors.green` in `index.js`, respectively. In @ghosh's screenshot the `color` hex value is different, but I am not familiar enough with Hyper theming to know if `colors.blue` is different in that screenshot or Hyper is rendering a different color from `colors` than `blue`.

**Comment by chilblane** [comment]
Further testing with other themes suggests this issue is unique to Bash on Ubuntu on Windows.

**Comment by ghosh** [comment]
@chilblane Thank you for helping pinpoint the source of the issue. Much appreciated.

Closing this issue for now, as it is not related to the theme.
