### ISSUE TITLE
Gray text invisible

### ISSUE THREAD

**Issue by tad-lispy** [Ghosh/hyperterm-solarized-dark#11]
The grey colored text is invisible (dark blue on dark blue). Unfortunately grey is used quite a lot, e.g. Node.js REPL by default colors `undefined` as grey, thus:

![hyper-solarized-dark-node-undefined-invisible](https://cloud.githubusercontent.com/assets/1684495/25434081/3835376c-2a8b-11e7-9f25-86ea533968bc.gif)

Changing value for `lightBlack` color [on line 7 of index.js](https://github.com/ghosh/hyper-solarized-dark/blob/193cd30b9915c3c47a0a559986f068d20afb2a41/index.js#L7) seems to fix the problem, but I'm not sure what the correct color would be. Now it's exactly the same as `backgroundColor` defined on line 1, i.e. `#002b36`.

**Comment by laedit** [comment]
Grey is also used for short param in powershell, like `-r`.

**Comment by ghosh** [comment]
@lzrski @laedit Thank you for bringing this to notice. I will fix it soon. 👍

**Comment by tad-lispy** [comment]
Thank you @ghosh. I really like your theme.

Locally I've set the colour to `#586e75`, which is what Solarized Dark theme for Atom Editor uses for comments. See [here (`@base01`)](https://github.com/atom/solarized-dark-syntax/blob/e620baebac182620c6ca214610bfbb41a85fce24/styles/colors.less#L10) and [here (`@syntax-comment-color`)](https://github.com/atom/solarized-dark-syntax/blob/918d70d2361db9f151d94d6c1213094e00615d90/styles/syntax-variables.less#L44).

 It looks pretty nice.

**Comment by ghosh** [comment]
@lzrski Thanks, that helped!

**Comment by raphaelproux** [comment]
Hi, I would like to bring this issue up since it has been reversed by commit 3a71436
The current version has this invisible text issue again.

**Comment by tad-lispy** [comment]
Maybe there should be a unit test? Something like: for each color assert that it is not the same as background color. You could even consider using something like https://github.com/bgrins/TinyColor#readability 😄

**Comment by jswny** [comment]
I can confirm that this issue appears again because of commit https://github.com/ghosh/hyper-solarized-dark/commit/3a71436a38758336fbe87505995f8f22725f7f00 as noted by @raphaelproux . Manually reversing the change in this commit in the local plugin `index.js` file fixes the issue.

@ghosh Can we get an update on why this issue was re-introduced and how to go about fixing it?

**Comment by ghosh** [comment]
@jswny I would happily accept a PR to fix this.

**Comment by jswny** [comment]
@ghosh Sent! Cheers :)

**Comment by ghosh** [comment]
@jswny Thank you. Released in `0.1.6`
