### ISSUE TITLE
Background color issue with solarized vim theme

### ISSUE THREAD

**Issue by welnanick** [Ghosh/hyperterm-solarized-dark#12]
I just installed this theme for hyper and there seems to be an issue when using vim and the solarized.vim theme, as the background color is incorrect and makes things illegible. See screenshot: 
<img width="964" alt="screen shot 2017-08-04 at 2 15 02 pm" src="https://user-images.githubusercontent.com/10217506/28987348-b6a9df98-791f-11e7-94af-8ebfaf9f1167.png">

Is there something I am doing wrong?

**Comment by welnanick** [comment]
This happens both in bash and zsh. For reference here are my OS details and such:

Hyper Version: 1.3.3.1754
Hyper Plugins: hypertheme, hyper-solarized-dark, hyper-nobold, hyper-tabs-enhanced, hyperline
zsh Version: 5.3.1
macOS Version: Sierra 10.12.6

I am using the vim colorscheme found [here](https://github.com/altercation/vim-colors-solarized), unmodified.

Thoughts?

**Comment by welnanick** [comment]
It also happens with the solarized colorscheme found [here](https://github.com/lifepillar/vim-solarized8).

EDIT: this theme works with `set termguicolors` in my .vimrc, the original theme still does not, however.

**Comment by ghosh** [comment]
@welnanick It seems to be a common issue in Hyper. There is a PR opened here - https://github.com/zeit/hyper/issues/155 

I am using OceanicNext until I figure this out. It works pretty well.

**Comment by welnanick** [comment]
Darn, well I have a workaround using solarized8-vim and setting termguicolors, but its not complete, some of my highlighting settings in my .vimrc are still not working. I hope hyper fixes it soon!

**Comment by ghosh** [comment]
Closing this for now, since it's not really a theme issue.
