### ISSUE TITLE
consider removing the font-feature-settings CSS?

### ISSUE THREAD

**Issue by jokeyrhyme** [Ghosh/hyperterm-solarized-dark#13]
Hiya, great theme!

I have been using this theme with Hyper 1.4.7 and the [Fira Mono](https://mozilla.github.io/Fira/) font family, and everything works wonderfully!

I just tried out Hyper 2.x canary to see what it was like, and I noticed that font ligatures were enabled which wasn't especially desirable for me

I tried adding a custom termCSS to turn it off, but I think the `!important` in this theme made it very difficult to disable

I'd suggest that this setting is very likely to be paired with the specific font that a user has set, so it might make more sense to drop it from the theme and allow the user to specify this together with their font? What do you think?

**Comment by ghosh** [comment]
@jokeyrhyme Yup, it makes sense. Thanks for bringing this up. I'll update the theme soon.

**Comment by jokeyrhyme** [comment]
@ghosh awesome! Would you like me to raise a PR?

**Comment by ghosh** [comment]
Sure, that would be great. Thank you.

**Comment by ghosh** [comment]
Thank you. I published the changes.
