### ISSUE TITLE
No visible split line when split vertically or horizonally

### ISSUE THREAD

**Issue by JasonBoy** [Ghosh/hyperterm-solarized-dark#15]
when in split mode, there is no sensible split line which makes the multiple shell window less noticeable, is this by design or there could be a fix?
<img width="711" alt="screen shot 2017-10-25 at 6 47 58 pm" src="https://user-images.githubusercontent.com/2911620/31995020-4dbbf012-b9b5-11e7-9aa9-3de584df9bbd.png">

**Comment by JayCarney** [comment]
Anybody have any followup on this? love the theme, would just make staring at a wall of text must easier if there was a divider

**Comment by estebanrao** [comment]
I fixed this adding 
```
    css: `
      .splitpane_divider {
        background-color: rgba(255,255,255,0.2)!important;
      }
    `,
``` 
to .hyper.js. Maybe this can be added to the theme

**Comment by benjefferies** [comment]
As @estebanrao said I also fixed by adding something similar

```
css: '.splitpane_divider { background-color: #586e75 !important; }',
```

I think this should be part of the plugin

**Comment by estebanrao** [comment]
Since the author haven't answered back I forked this repo, fixed this issue and created a new plugin for hyper calles hyper-solarized-dark2 in https://github.com/estebanrao/hyper-solarized-dark
