### ISSUE TITLE
Colors clashing with vim solarized dark theme

### ISSUE THREAD

**Issue by sethetter** [Ghosh/hyperterm-solarized-dark#19]
Looks like updating `lightBlack` to `#002b36` does the trick!

Before:
![image](https://user-images.githubusercontent.com/655500/38563201-e6b8a8ea-3ca1-11e8-8787-480670b95cfc.png)
After:
![image](https://user-images.githubusercontent.com/655500/38563250-ffc184ce-3ca1-11e8-9bb4-a9208c477fd1.png)

**Comment by estebanrao** [comment]
Since the author haven't answered back I forked this repo, fixed this issue and created a new plugin for hyper calles hyper-solarized-dark2 in https://github.com/estebanrao/hyper-solarized-dark

**Comment by ghosh** [comment]
Fixed in #17.
