### ISSUE TITLE
Uneven background color

### ISSUE THREAD

**Issue by scottgrayson** [Ghosh/hyperterm-solarized-dark#9]
![image](https://cloud.githubusercontent.com/assets/7796074/22620557/68efec38-eadc-11e6-979e-79eac3ceeaa9.png)
The background behind text is different than the background without text.
It actually blinks back to normal if i hover over the top tab bar.

**Comment by ghosh** [comment]
@scottgrayson  Thanks for the heads up. I am actually not being able to replicate this. 
Have you overridden any styles in your config? Also what display are you on?

**Comment by ghosh** [comment]
Closing, as cannot recreate.
